create table public.arquiva_folders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null
    constraint arquiva_folders_name_check
    check (
      name = btrim(name)
      and char_length(name) between 1 and 60
      and name !~ '[[:cntrl:]]'
    ),
  color text not null default 'mint'
    constraint arquiva_folders_color_check
    check (color in ('mint', 'peach', 'lilac', 'sky')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint arquiva_folders_id_user_unique unique (id, user_id)
);

create unique index arquiva_folders_user_name_unique
  on public.arquiva_folders (user_id, lower(name));

create index arquiva_folders_user_sort_idx
  on public.arquiva_folders (user_id, sort_order, name);

create table public.arquiva_files (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  folder_id bigint,
  name text not null
    constraint arquiva_files_name_check
    check (
      name = btrim(name)
      and char_length(name) between 1 and 160
      and name !~ '[[:cntrl:]]'
    ),
  drive_file_id text not null unique
    constraint arquiva_files_drive_file_id_check
    check (char_length(drive_file_id) between 1 and 255),
  drive_guard uuid not null unique,
  mime_type text not null
    constraint arquiva_files_mime_type_check
    check (char_length(mime_type) between 1 and 255),
  size_bytes bigint not null
    constraint arquiva_files_size_check
    check (size_bytes > 0 and size_bytes <= 26214400),
  is_favorite boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  trashed_at timestamptz,
  constraint arquiva_files_folder_owner_fkey
    foreign key (folder_id, user_id)
    references public.arquiva_folders (id, user_id)
    on delete set null (folder_id)
);

create index arquiva_files_user_id_idx
  on public.arquiva_files (user_id);

create index arquiva_files_folder_id_idx
  on public.arquiva_files (folder_id);

create index arquiva_files_user_live_idx
  on public.arquiva_files (user_id, updated_at desc)
  where trashed_at is null;

create index arquiva_files_user_folder_live_idx
  on public.arquiva_files (user_id, folder_id, updated_at desc)
  where trashed_at is null;

create index arquiva_files_user_favorites_idx
  on public.arquiva_files (user_id, updated_at desc)
  where is_favorite and trashed_at is null;

create index arquiva_files_user_trash_idx
  on public.arquiva_files (user_id, trashed_at desc)
  where trashed_at is not null;

alter table public.arquiva_folders enable row level security;
alter table public.arquiva_folders force row level security;
alter table public.arquiva_files enable row level security;
alter table public.arquiva_files force row level security;

revoke all on table public.arquiva_folders from public, anon;
revoke all on table public.arquiva_files from public, anon;
revoke all on sequence public.arquiva_folders_id_seq from public, anon;
revoke all on sequence public.arquiva_files_id_seq from public, anon;

grant select, insert, update, delete
  on table public.arquiva_folders, public.arquiva_files
  to authenticated;
grant usage, select
  on sequence public.arquiva_folders_id_seq, public.arquiva_files_id_seq
  to authenticated;

create policy arquiva_folders_select_own
  on public.arquiva_folders
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy arquiva_folders_insert_own
  on public.arquiva_folders
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy arquiva_folders_update_own
  on public.arquiva_folders
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy arquiva_folders_delete_own
  on public.arquiva_folders
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

create policy arquiva_files_select_own
  on public.arquiva_files
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy arquiva_files_insert_own
  on public.arquiva_files
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy arquiva_files_update_own
  on public.arquiva_files
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy arquiva_files_delete_own
  on public.arquiva_files
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);
